name: Release

on:
  schedule:
    # Try a couple of times every Monday
    - cron: '50 6,7,8,9 * * 1'
  # Allows manual trigger from GitHub UI
  workflow_dispatch:


jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "Release Bot"
          git config user.email "release@waydro.id"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout master
        run: git checkout master

      - name: Merge staging into master
        run: git merge origin/staging --no-edit

      - name: Push master
        run: git push origin master
